echo '--------------------------------------------'
echo 'Tugas 1 SISOP Kelas-A'
echo '--------------------------------------------'
echo 'Nama: Adhisa Shilfadianis Iffadah'
echo 'NPM : 21083010016'
echo '--------------------------------------------'
echo 'notes:'
echo '--------------------------------------------'
echo 'Halo Dunia!'
echo 'Ini adalah skrip Bash pertamaku di Linux'
